name:                images-to-md
version:             0.1.0.0
github:              "githubuser/images-to-md"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/images-to-md#readme>

dependencies:
- base >= 4.7 && < 5
- effectful
- effectful-core
- gogol
- gogol-core
- gogol-vision
- optparse-applicative
- directory
- filepath
- text
- bytestring
- aeson
- lens
- unix

default-extensions:
- DataKinds
- TypeFamilies
- OverloadedStrings
- RecordWildCards
- LambdaCase
- DerivingStrategies
- GADTs

library:
  source-dirs: src

executables:
  images-to-md-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - images-to-md

tests:
  images-to-md-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - images-to-md
